### ISSUE TITLE
gen id as a function

### ISSUE THREAD

**Issue by qyloxe** [turbo/pg-shortkey#1]
This fragment:

```
      gkey := encode(gen_random_bytes(8), 'base64');
      gkey := replace(gkey, '/', '_');  -- url safe replacement
      gkey := replace(gkey, '+', '-');  -- url safe replacement
      key := rtrim(gkey, '=');          -- cut off padding
```

Could be implemented as another function with parameter `keylen` (defaults to 8). This method allows to use this function in your other inserts, updates - or even change your default gen function for another one - for example with default of 10 bytes or based on uuid with some prefix, sufix.

**Comment by turbo** [comment]
Feel free to open a PR 👍 . Closing this, as this isn't a bug.
