### ISSUE TITLE
Use EXIT WHEN ... rather than IF ... THEN EXIT; END IF

### ISSUE THREAD

**Issue by mmauger** [turbo/pg-shortkey#2]
https://github.com/turbo/pg-shortkey/blob/90dbb5f5e68840786d2604f333a0907451fdae0c/pg-shortkey.sql#L53

This is better coded as:
>    EXIT WHEN found IS NULL;

**Comment by turbo** [comment]
Feel free to open a PR 👍 . Closing this, as this isn't a bug.
